name: Deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: asylum

    steps:
      - name: Checkout code.
        uses: actions/checkout@v2

      - name: Maven clean install
        run: mvn clean install --file pom.xml
          
      - name: Stop the manager.
        run: sudo screen -XS manager quit

      - name: Replace jar.
        run: sudo cp ./target/Manager.jar /home/pulse/manager/Manager.jar

      - name: Start manager.
        run: cd /home/pulse/manager && sudo screen -S manager -dm ./start.sh
